[package]
authors     = ["knrew"]
description = "A Rust library for competitive programming, mainly targeting AtCoder."
edition     = "2024"
name        = "reprol"
publish     = false
version     = "2.0.0"

[dependencies]

[dev-dependencies]
rand = "0.9.2"
