name: Rust

on:
  workflow_call:
    inputs:
      rust_toolchain:
        type: string
        required: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  fmt:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ inputs.rust_toolchain }}
          components: rustfmt
      - run: cargo +${{ inputs.rust_toolchain }} fmt --all --check --verbose

  clippy:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ inputs.rust_toolchain }}
          components: clippy
      - run: cargo +${{ inputs.rust_toolchain }} clippy --workspace --all-features -- -D warnings

  check:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ inputs.rust_toolchain }}
      - run: cargo +${{ inputs.rust_toolchain }} check --workspace --all-targets --all-features --verbose
      - run: cargo +${{ inputs.rust_toolchain }} check --release --workspace --all-targets --all-features --verbose

  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ inputs.rust_toolchain }}
      - run: cargo +${{ inputs.rust_toolchain }} test --workspace --all-features --no-fail-fast --verbose
      - run: cargo +${{ inputs.rust_toolchain }} test --release --workspace --all-features --no-fail-fast --verbose
